### ISSUE TITLE
app has no notifications

### ISSUE THREAD

**Issue by sosasees** [prof18/feed-flow#343] opened 2024-12-03 07:53 UTC
yesterday i noticed that [Feeder](https://f-droid.org/packages/com.nononsenseapps.feeder/) has anti&#x2011;features according to F&#x2011;Droid, so i looked for another feedreader on F&#x2011;Droid.
Feeder's neighboring search&nbsp;result for ``feed`` is FeedFlow. it has no anti&#x2011;features and looks to have nearly the same UI&nbsp;design, so i moved from Feeder to FeedFlow, almost certain that FeedFlow would be a good drop&#x2011;in&nbsp;replacement.

FeedFlow almost is a great replacement for Feeder. only one important feature is missing: notifications when new articles are released.
for me, the point of having a feedreader installed is these notifications, so i don't have to keep checking for if new articles are released: only reading new articles when my mobile&nbsp;device lets me know that they are released.
(if i didn't need these notifications, i could just go to the websites to read the articles.)

the lack of notifications is not an issue for many users since they check their feeds everyday anyway
but i only read feeds that only update occasionally, so notifications are important to not waste time to look into the app when most&nbsp;times there are no new articles

**Comment by prof18** [comment] 2024-12-12 14:47
Thanks for the suggestion, I will consider that in the future.

**Comment by prof18** [comment] 2024-12-19 22:08
Closing as duplicate of https://github.com/prof18/feed-flow/issues/2

**Closed by prof18** 2024-12-19 22:08 UTC
