### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by KasimiraEike** [prof18/feed-flow#110] opened 2024-01-08 17:14 UTC
Do you plan to release [FeedFlow](https://www.feedflow.dev/) on [F-Droid](https://f-droid.org/)?

**Comment by prof18** [comment] 2024-01-14 15:27
Yes, I'm planning to do soon!

**Comment by shuvashish76** [comment] 2024-09-03 10:58
Requested at F-Droid: https://gitlab.com/fdroid/rfp/-/issues/2870

**Comment by licaon-kter** [comment] 2024-09-03 11:20
Fastlane (https://gitlab.com/-/snippets/1895688) ?

Reproducible builds (https://f-droid.org/docs/Inclusion_How-To/#reproducible-builds) ?

Flavor without non-FLOSS Firebase/Crashlytics ?

**Comment by prof18** [comment] 2024-09-04 09:57
Yes, I have to create a flavor without Crashlytics and probably without the Dropbox sync because I don't know where to save the API key for the FDroid build

**Comment by prof18** [comment] 2024-09-13 21:12
Update: Merge Request sent to FDroid: https://gitlab.com/fdroid/fdroiddata/-/merge_requests/15755

**Comment by sette15** [comment] 2024-09-14 09:31
that's great, thanks! It'd be fantastic if you could also release a FOSS apk version here in github, so whoever is using Obtainium would definitely benefit that. thanks

**Comment by sette15** [comment] 2024-09-14 17:57
@codenyte oh yea, I know. the only issue is that f-droid releases slowler than the ones on github

**Comment by shuvashish76** [comment] 2024-09-23 08:57
Live on F-Droid 🎉, feel free to use their badge : https://gitlab.com/fdroid/artwork/-/blob/master/badge/README.md

You can close this issue now, ThankYou.

**Comment by prof18** [comment] 2024-09-23 20:21
Yes, I will update the readme and the website soon

**Closed by prof18** 2024-09-23 20:21 UTC

**Comment by chrysle** [comment] 2024-12-27 09:56
When do we get the newer versions on F-Droid? Can't wait for the new editing feature!

**Comment by prof18** [comment] 2024-12-27 09:58
Depends on how fast Fdroid is in building the app! Could be up to 7days!

**Comment by Coool** [comment] 2025-05-09 18:42
> Yes, I have to create a flavor without Crashlytics and probably without the Dropbox sync because I don't know where to save the API key for the FDroid build

What else is different between the Google Play and F-Droid versions?
